version: 1.0.3.{build}

branches:
  only:
    - master

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m

nuget:
  disable_publish_on_pr: true

build_script:
  - pwsh: dotnet pack -c Release

artifacts:
  - path: \Emerlahn.AwsSsm\bin\Release\*.nupkg
    name: Emerlahn.AwsSsm

deploy:
  - provider: NuGet
    name: Production
    server:
    api_key:
      secure: pEEcr9Q18gv57zbNi0HFDlMBcY7/peFMBP40cYGyezyaR7Tlba4cX2887ksONfJS
    tag: $(APPVEYOR_REPO_TAG_NAME)
    on:
      branch: master
      appveyor_repo_tag: true